services:
  db:
    image: postgres:17
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mosaic
    ports:
      - "5432:5432"
    networks:
      - mosaic-net

volumes:
  db-data:

networks:
  mosaic-net:
    driver: bridge
  proxy:
    external: true